/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package music.blog;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hasin Sadique
 */
public class DetailsPage extends javax.swing.JFrame {

    /**
     * Creates new form DetailsPage
     */
    int SID;
    String email;
    int UIDArtist;
    int UIDMainUser;
    int like;
    Object S=null;
    public DetailsPage() {
        initComponents();
        
        
        
    }
    public void getDetails(Object s, String Email){
        S=s;
        email=Email;
        //set values
        PreparedStatement ps;
        ResultSet rs;
        ResultSet rs2;
        String query1="SELECT * FROM `songs_table` WHERE `Song_ID`=?";
        String query2="SELECT Full_Name FROM `user` WHERE `User_ID`=?";
        String Query3="SELECT * FROM `user` WHERE `Email` = ?";
            try {
                ps=MyConnection.getConnection().prepareStatement(query1);
                System.out.println(" korse");
                
                ps.setString(1, s.toString());
                System.out.println("boshe");
                rs=ps.executeQuery();
                System.out.println("query 1 kaj korse");
                if(rs.next()){
                    jLabel_SongName.setText(rs.getString("Song_Name"));
                    jTextArea_desc.setText(rs.getString("Description"));
                    SID=rs.getInt("Song_ID");
                    UIDArtist=rs.getInt("UID");
                    
                }else{
                
                } 
                ps=MyConnection.getConnection().prepareStatement(query2);
                ps.setInt(1, rs.getInt("UID"));
                rs2=ps.executeQuery();
                System.out.println("UID paisi");
                if(rs2.next()){
                        jLabel_ArtistName.setText(rs2.getString("Full_Name"));
            
                }else{
                
                }
                
                ps=MyConnection.getConnection().prepareStatement(Query3);
                ps.setString(1, email);
                rs=ps.executeQuery();
                if(rs.next()){
                    UIDMainUser=rs.getInt("User_ID");
                }else{}
                
            } catch (SQLException ex) {
                Logger.getLogger(LoginAndRegistration.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_SongName = new javax.swing.JLabel();
        jLabel_ArtistName = new javax.swing.JLabel();
        jButton_FollowArist = new javax.swing.JButton();
        jLabel_Description = new javax.swing.JLabel();
        jButton_Like = new javax.swing.JButton();
        jButton_CommentBT_ = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_desc = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(47, 43, 43));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Details");

        jPanel3.setForeground(new java.awt.Color(60, 63, 65));

        jLabel_SongName.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_SongName.setText("Song Name");

        jLabel_ArtistName.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ArtistName.setText("Artist Name");

        jButton_FollowArist.setBackground(java.awt.Color.gray);
        jButton_FollowArist.setText("Follow");
        jButton_FollowArist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FollowAristActionPerformed(evt);
            }
        });

        jLabel_Description.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Description.setText("Description");

        jButton_Like.setText("Like");
        jButton_Like.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LikeActionPerformed(evt);
            }
        });

        jButton_CommentBT_.setText("Comment");
        jButton_CommentBT_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CommentBT_ActionPerformed(evt);
            }
        });

        jButton3.setText("Download");

        jTextArea_desc.setBackground(new java.awt.Color(47, 43, 43));
        jTextArea_desc.setColumns(20);
        jTextArea_desc.setRows(5);
        jScrollPane1.setViewportView(jTextArea_desc);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jButton_Like, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton_CommentBT_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_SongName, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel_ArtistName, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_FollowArist))
                            .addComponent(jLabel_Description, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_SongName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ArtistName)
                    .addComponent(jButton_FollowArist))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Description)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_CommentBT_)
                    .addComponent(jButton_Like)
                    .addComponent(jButton3))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_FollowAristActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FollowAristActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps;
        ResultSet rs;
        String Query1="INSERT INTO `followers`(`Followed`, `Follower`) VALUES (?,?)";
        String Query2="SELECT * FROM `user` WHERE `Email` = ?";
            try {
                ps=MyConnection.getConnection().prepareStatement(Query2);
                ps.setString(1, email);
                rs=ps.executeQuery();
                if(rs.next()){
                    UIDMainUser=rs.getInt("User_ID");
                }else{}
                ps=MyConnection.getConnection().prepareStatement(Query1);
                ps.setInt(1, UIDArtist);
                ps.setInt(2, UIDMainUser);
                if(ps.executeUpdate()!=0){
                    JOptionPane.showMessageDialog(null, "You are a follower");
                }else{}
                
                
            } catch (SQLException ex) {
                Logger.getLogger(LoginAndRegistration.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_jButton_FollowAristActionPerformed

    private void jButton_LikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LikeActionPerformed
        // TODO add your handling code here:
        
        PreparedStatement ps;
        ResultSet rs;
        String query1="SELECT * FROM `songs_table` WHERE `Song_ID`=?";
        String query2="UPDATE `songs_table` SET `likes`= ? WHERE `Song_ID`= ?";
            try {
                ps=MyConnection.getConnection().prepareStatement(query1);
                ps.setInt(1, SID);
                rs=ps.executeQuery();
                System.out.println("like query 1 kaj korse");
                if(rs.next()){
                    like = rs.getInt("likes");
                }else{
                
                }
                like++;
                ps=MyConnection.getConnection().prepareStatement(query2);
                ps.setInt(1, like);
                ps.setInt(2, SID);
                int r = ps.executeUpdate();
                if(r!=0){
                    JOptionPane.showMessageDialog(null, "You just liked a Song");
                }else{
                
                }
            } catch (SQLException ex) {
                Logger.getLogger(LoginAndRegistration.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton_LikeActionPerformed

    private void jButton_CommentBT_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CommentBT_ActionPerformed
        // TODO add your handling code here:
        
        CommentPage cp= new CommentPage();
        cp.sendInfo(SID,UIDMainUser);
        cp.setVisible(true);
        cp.pack();
        cp.setLocationRelativeTo(null);
        cp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
    }//GEN-LAST:event_jButton_CommentBT_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DetailsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_CommentBT_;
    private javax.swing.JButton jButton_FollowArist;
    private javax.swing.JButton jButton_Like;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_ArtistName;
    private javax.swing.JLabel jLabel_Description;
    private javax.swing.JLabel jLabel_SongName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_desc;
    // End of variables declaration//GEN-END:variables
}
