/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package music.blog;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hasin Sadique
 */
public class Homepage extends javax.swing.JFrame {
    String Email;
    /**
     * Creates new form Homepage
     */
    
    DefaultTableModel model;
    public Homepage() {
      //  UName=name;
        initComponents();
        PreparedStatement ps;
        ResultSet rs;
        String query="SELECT * FROM `songs_table` WHERE `Song_Name`=?";
        
        try{
            ps=MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, Email);
            rs=ps.executeQuery();
            if(rs.next()){
               String Name=rs.getString("Full_Name");
                jLabel_AccountP_Name.setText(Name);
            }

            
        }catch (SQLException ex) {
            Logger.getLogger(LoginAndRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
        //jList_DisplayList.setModel(new DefaultListModel<String>());
        model=(DefaultTableModel) jTable_HomeTable.getModel();
        
    }
        
    
    public void createSession(String email){
        Email=email;
        System.out.println("session created= "+ email);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser2 = new javax.swing.JFileChooser();
        jDialog1 = new javax.swing.JDialog();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        uploadMusic = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField_searchField = new javax.swing.JTextField();
        jButton_Search_ = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton_myUploads = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_HomeTable = new javax.swing.JTable();
        jButton_Details = new javax.swing.JButton();
        jLabel_AccountP_Name = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(47, 43, 43));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Segoe Script", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Music Blog");
        jLabel1.setToolTipText("");

        jButton1.setBackground(new java.awt.Color(47, 43, 43));
        jButton1.setText("My Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        uploadMusic.setBackground(new java.awt.Color(47, 43, 43));
        uploadMusic.setText("Upload Music");
        uploadMusic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uploadMusicMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                uploadMusicMouseEntered(evt);
            }
        });
        uploadMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadMusicActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(47, 43, 43));
        jButton3.setText("Downloaded Music");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField_searchField.setBackground(new java.awt.Color(68, 61, 61));
        jTextField_searchField.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_searchFieldActionPerformed(evt);
            }
        });

        jButton_Search_.setText("Search");
        jButton_Search_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Search_MouseClicked(evt);
            }
        });
        jButton_Search_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Search_ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(47, 43, 43));
        jButton5.setText("Sign out");

        jPanel2.setBackground(new java.awt.Color(255, 128, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Trending");

        jButton_myUploads.setBackground(new java.awt.Color(47, 43, 43));
        jButton_myUploads.setText("My Uploads");
        jButton_myUploads.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton_myUploadsMouseMoved(evt);
            }
        });
        jButton_myUploads.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_myUploadsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_myUploadsMouseEntered(evt);
            }
        });
        jButton_myUploads.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_myUploadsActionPerformed(evt);
            }
        });

        jTable_HomeTable.setForeground(new java.awt.Color(47, 43, 43));
        jTable_HomeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Song ID", "Song Name", "Artist Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_HomeTable.setSelectionForeground(new java.awt.Color(47, 43, 43));
        jTable_HomeTable.getTableHeader().setReorderingAllowed(false);
        jTable_HomeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_HomeTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_HomeTable);
        jTable_HomeTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jButton_Details.setText("Details");
        jButton_Details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_DetailsMouseClicked(evt);
            }
        });
        jButton_Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DetailsActionPerformed(evt);
            }
        });

        jLabel_AccountP_Name.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(uploadMusic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_myUploads, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_AccountP_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField_searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Search_, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Details)
                            .addGap(226, 226, 226))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Search_))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_AccountP_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uploadMusic, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_myUploads, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jButton_Details))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void uploadMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadMusicActionPerformed
      uploadPage uPage= new uploadPage();
        uPage.sendSession(Email);
        uPage.setVisible(true);
        uPage.pack();
        uPage.setLocationRelativeTo(null);
        uPage.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_uploadMusicActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField_searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_searchFieldActionPerformed

    private void jButton_Search_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Search_ActionPerformed
        // TODO add your handling code here:
        ArrayList<Song> SongList=new ArrayList<>();
        String srch = jTextField_searchField.getText();
        PreparedStatement ps;
        ResultSet rs;
        String query="SELECT * FROM `songs_table` WHERE `Song_Name`=?";
            try {
                ps=MyConnection.getConnection().prepareStatement(query);
                ps.setString(1, srch);
                rs=ps.executeQuery();
                                
                while(rs.next()){
                    //rs.getInt("Song_ID");
                    //((DefaultListModel)jList_DisplayList.getModel()).addElement(rs.getString("Song_Name"));
                    //((DefaultListModel)jList_DisplayList.getModel()).addElement(rs.getInt("UID"));
                    //((DefaultListModel)jList_DisplayList.
                    int SID=rs.getInt("Song_ID");
                    int UserID=rs.getInt("UID");
                    String SongName=rs.getString("Song_Name");
                    Song s=new Song(SID,UserID,SongName);
                    SongList.add(s);
                }
                //loop for displaying songs on table
                
                DefaultTableModel model = new DefaultTableModel();
                model.setColumnIdentifiers(new Object[]{"Song ID","Song Name","Artist Name"});
                Object[] col = new Object[3];
                
                for(int i=0;i<SongList.size();i++){
                    col[0]=SongList.get(i).getSongID();
                    col[1]=SongList.get(i).getUID();
                    col[2]=SongList.get(i).getSongName();
                    model.addRow(col);
                    
                }
                jTable_HomeTable.setModel(model);
                //jTable_HomeTable.setRowSelectionAllowed(true);
                                
            } catch (SQLException ex) {
                Logger.getLogger(LoginAndRegistration.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_jButton_Search_ActionPerformed

    private void uploadMusicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadMusicMouseClicked
       /* // TODO add your handling code here
       //go to upload music screen
        uploadPage up= new uploadPage();
        up.sendSession(Email);
        up.setVisible(true);
        up.pack();
        up.setLocationRelativeTo(null);
        //up.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
     */   
    }//GEN-LAST:event_uploadMusicMouseClicked

    private void uploadMusicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadMusicMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_uploadMusicMouseEntered

    private void jButton_myUploadsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_myUploadsMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton_myUploadsMouseClicked

    private void jButton_myUploadsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_myUploadsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_myUploadsMouseEntered

    private void jButton_myUploadsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_myUploadsActionPerformed
        // TODO add your handling code here:
        myUploads myUps= new myUploads();
        myUps.sendSession(Email);
        myUps.setVisible(true);
        myUps.pack();
        myUps.setLocationRelativeTo(null);
        myUps.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_jButton_myUploadsActionPerformed

    private void jButton_myUploadsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_myUploadsMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_myUploadsMouseMoved

    private void jButton_Search_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Search_MouseClicked
     // TODO add your handling code here:
     
    }//GEN-LAST:event_jButton_Search_MouseClicked

    private void jTable_HomeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_HomeTableMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTable_HomeTableMouseClicked

    private void jButton_DetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DetailsActionPerformed
        // TODO add your handling code here:
              
    }//GEN-LAST:event_jButton_DetailsActionPerformed

    private void jButton_DetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_DetailsMouseClicked
        // TODO add your handling code here:
        int row=jTable_HomeTable.getSelectedRow();
        Object s=jTable_HomeTable.getValueAt(row,0);
        //JOptionPane.showMessageDialog(null, s);
        DetailsPage DP=new DetailsPage();
        DP.getDetails(s,Email);
        DP.setVisible(true);
        DP.pack();
        DP.setLocationRelativeTo(null);
        DP.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton_DetailsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton_Details;
    private javax.swing.JButton jButton_Search_;
    private javax.swing.JButton jButton_myUploads;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_AccountP_Name;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_HomeTable;
    private javax.swing.JTextField jTextField_searchField;
    private javax.swing.JButton uploadMusic;
    // End of variables declaration//GEN-END:variables
}
