/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package music.blog;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Hasin Sadique
 */
public class uploadPage extends javax.swing.JFrame {
    
    String s;
    String email;
    
    /**
     * Creates new form uploadPage
     */
    public uploadPage() {
        initComponents();
    }
    
    public void sendSession(String Email){
        email=Email;
        System.out.println("email= "+email);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_browsedFile = new javax.swing.JTextField();
        jButton_Browse_ = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_SongName = new javax.swing.JTextField();
        jButton1_CancelUpload_ = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Description = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField_browsedFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_browsedFileActionPerformed(evt);
            }
        });

        jButton_Browse_.setText("Browse");
        jButton_Browse_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Browse_ActionPerformed(evt);
            }
        });

        jButton2.setText("Upload Music");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Upload MUsic File");

        jLabel2.setText("Song Name:");

        jButton1_CancelUpload_.setText("Cancel");
        jButton1_CancelUpload_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_CancelUpload_ActionPerformed(evt);
            }
        });

        jLabel3.setText("Description");

        jTextArea_Description.setColumns(20);
        jTextArea_Description.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Description);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jButton1_CancelUpload_, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_SongName)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField_browsedFile, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton_Browse_))
                                            .addComponent(jScrollPane1))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(30, 30, 30)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(jTextField_SongName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_browsedFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Browse_))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_CancelUpload_)
                    .addComponent(jButton2))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Browse_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Browse_ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        /*chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        String filename=f.getAbsolutePath();
        jTextField_browsedFile.setText(filename);*/
        
//        chooser.setCurrentDirectory(new File(System.getProperty("User.home")));
        FileNameExtensionFilter filter=new FileNameExtensionFilter("mp3","wav");
        chooser.addChoosableFileFilter(filter);
        int result =chooser.showSaveDialog(null);
        if(result == chooser.APPROVE_OPTION){
            File selectedFile=chooser.getSelectedFile();
            String path=selectedFile.getAbsolutePath();
            s=path;
            jTextField_browsedFile.setText(path);
            
        }else if(result==JFileChooser.CANCEL_OPTION){
            System.out.println("No Data");
        }
        
    }//GEN-LAST:event_jButton_Browse_ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
//        PreparedStatement ps;
//            String query="INSERT INTO `songs_table`(`Song_Name`, `Content`) VALUES (?,?)";
//            try {
//                ps=MyConnection.getConnection().prepareStatement(query);
//                InputStream is=new FileInputStream(new File(s));
//                ps.setString(1, jTextField_SongName.getText());
//                ps.setBlob(2, is);
//                ps.executeUpdate();
//                JOptionPane.showMessageDialog(null, "File Inserted");
//                if(ps.executeUpdate()>0){
//                    //JOptionPane.showMessageDialog(null, "New User Added");
//                }
//            }catch (Exception ex) {
//                //Logger.getLogger(Registration_Page.class.getName()).log(Level.SEVERE, null, ex);
//                ex.printStackTrace();
//            } 
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here
        
        PreparedStatement ps;
            String query1="SELECT `User_ID` FROM `user` WHERE `Email`=?";
            String query2="INSERT INTO `songs_table`(`UID`,`Song_Name`,`Content`, `Description`) VALUES (?,?,?,?)";
            try {
                int UID=0;
                ps=MyConnection.getConnection().prepareStatement(query1);
                //InputStream is=new FileInputStream(new File(s));
                
                ps.setString(1, email);
                ResultSet rs =ps.executeQuery();
                if(rs.next()){
                    UID=rs.getInt("User_ID");
                
                }
                JOptionPane.showMessageDialog(null, UID);
                
                ps=MyConnection.getConnection().prepareStatement(query2);
                InputStream is=new FileInputStream(new File(s));
                ps.setInt(1, UID);
                ps.setString(2, jTextField_SongName.getText());
                ps.setBlob(3, is);
                ps.setString(4, jTextArea_Description.getText());
                
                ps.executeUpdate();
                this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                JOptionPane.showMessageDialog(null, "File Inserted");
                
            }catch (Exception ex) {
                ex.printStackTrace();
            }    //Logger.getLogger(Registration_Page.class.getName()).log(Level.SEVERE, null, ex);
             
    }//GEN-LAST:event_jButton2MouseClicked

    private void jTextField_browsedFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_browsedFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_browsedFileActionPerformed

    private void jButton1_CancelUpload_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_CancelUpload_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_CancelUpload_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uploadPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uploadPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uploadPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uploadPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uploadPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_CancelUpload_;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_Browse_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_Description;
    private javax.swing.JTextField jTextField_SongName;
    private javax.swing.JTextField jTextField_browsedFile;
    // End of variables declaration//GEN-END:variables
}
